export const countryData = [
  { id: 1, name: "United States" },
  { id: 2, name: "India" },
  { id: 3, name: "United Kingdom" },
  { id: 4, name: "Canada" },
  { id: 5, name: "Australia" },
  { id: 6, name: "Germany" },
  { id: 7, name: "France" },
  { id: 8, name: "Brazil" },
  { id: 9, name: "China" },
  { id: 10, name: "Japan" },
  { id: 11, name: "South Africa" },
  { id: 12, name: "Russia" },
  { id: 13, name: "Italy" },
  { id: 14, name: "Spain" },
  { id: 15, name: "Mexico" },
  { id: 16, name: "Argentina" },
  { id: 17, name: "Netherlands" },
  { id: 18, name: "Sweden" },
  { id: 19, name: "Norway" },
  { id: 20, name: "Denmark" },
  { id: 21, name: "Switzerland" },
  { id: 22, name: "India" },
  { id: 23, name: "South Korea" },
  { id: 24, name: "New Zealand" },
  { id: 25, name: "Singapore" },
  { id: 26, name: "Greece" },
  { id: 27, name: "Ireland" },
  { id: 28, name: "Austria" },
  { id: 29, name: "Belgium" },
  { id: 30, name: "Finland" },
  { id: 31, name: "Portugal" },
  { id: 32, name: "Poland" },
  { id: 33, name: "Turkey" },
  { id: 34, name: "Egypt" },
  { id: 35, name: "Kenya" },
  { id: 36, name: "Nigeria" },
  { id: 37, name: "South Africa" },
  { id: 38, name: "Saudi Arabia" },
  { id: 39, name: "United Arab Emirates" },
  { id: 40, name: "Thailand" },
  { id: 41, name: "Vietnam" },
  { id: 42, name: "Malaysia" },
  { id: 43, name: "Indonesia" },
  { id: 44, name: "Philippines" },
  { id: 45, name: "Mexico" },
  { id: 46, name: "Colombia" },
  { id: 47, name: "Peru" },
  { id: 48, name: "Chile" },
  { id: 49, name: "Argentina" },
  { id: 50, name: "Brazil" },
];
